GET {{URL}}}/
Accept: application/json

###
GET {{URL}}/tool/network?chain_id=56
Accept: application/json

###
###
# 获取最新的区块高度信息 by network
GET http://54.251.226.240:9006/block/last?network=goerli



